int[] grades = new int[5];
string[] daysofweeks = new string[7];
daysofweeks[0] = "poniedziałek";
daysofweeks[1] = "wtorek";
daysofweeks[2] = "środa";
daysofweeks[3] = "czwartek";
daysofweeks[4] = "piątek";
daysofweeks[5] = "sobota";
daysofweeks[6] = "niedziela";
Console.WriteLine(daysofweeks[5]);